### ISSUE TITLE
Colour Temperature and Brightness adjustment options

### ISSUE THREAD

**Issue by Luminus** [raine/Lolgato#2]
Thanks for this app @raine, 

Being able to turn my lights on and off without having to reach for the mouse and hunt around is such a pleasure.

Would it be possible to add the option for keyboard shortcuts to adjust the colour temperature and brightness of the lights? Right now, one still needs to rely on the Elgato Control Center for this.

Thanks loads.

**Comment by raine** [comment]
Hey, I'm glad you find it useful.

I've added the shortcuts in the latest version just now.

Let me know if it doesn't work for you for some reason.

**Comment by Luminus** [comment]
You absolute legend. Thanks for super quick turnaround.
